package main

import "github.com/hajimehoshi/ebiten/v2"

var USNormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'a', ebiten.KeyB: 'b', ebiten.KeyC: 'c', ebiten.KeyD: 'd',
	ebiten.KeyE: 'e', ebiten.KeyF: 'f', ebiten.KeyG: 'g', ebiten.KeyH: 'h',
	ebiten.KeyI: 'i', ebiten.KeyJ: 'j', ebiten.KeyK: 'k', ebiten.KeyL: 'l',
	ebiten.KeyM: 'm', ebiten.KeyN: 'n', ebiten.KeyO: 'o', ebiten.KeyP: 'p',
	ebiten.KeyQ: 'q', ebiten.KeyR: 'r', ebiten.KeyS: 's', ebiten.KeyT: 't',
	ebiten.KeyU: 'u', ebiten.KeyV: 'v', ebiten.KeyW: 'w', ebiten.KeyX: 'x',
	ebiten.KeyY: 'y', ebiten.KeyZ: 'z',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: '[', ebiten.KeyBracketRight: ']',
	ebiten.KeyBackslash: '\\', ebiten.KeySemicolon: ';',
	ebiten.KeyQuote: '\'', ebiten.KeyBackquote: '`',
	ebiten.KeyComma: ',', ebiten.KeyPeriod: '.', ebiten.KeySlash: '/',
	ebiten.KeySpace: ' ',
}

var USShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'A', ebiten.KeyB: 'B', ebiten.KeyC: 'C', ebiten.KeyD: 'D',
	ebiten.KeyE: 'E', ebiten.KeyF: 'F', ebiten.KeyG: 'G', ebiten.KeyH: 'H',
	ebiten.KeyI: 'I', ebiten.KeyJ: 'J', ebiten.KeyK: 'K', ebiten.KeyL: 'L',
	ebiten.KeyM: 'M', ebiten.KeyN: 'N', ebiten.KeyO: 'O', ebiten.KeyP: 'P',
	ebiten.KeyQ: 'Q', ebiten.KeyR: 'R', ebiten.KeyS: 'S', ebiten.KeyT: 'T',
	ebiten.KeyU: 'U', ebiten.KeyV: 'V', ebiten.KeyW: 'W', ebiten.KeyX: 'X',
	ebiten.KeyY: 'Y', ebiten.KeyZ: 'Z',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '@', ebiten.KeyDigit3: '#',
	ebiten.KeyDigit4: '$', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: '^',
	ebiten.KeyDigit7: '&', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: '{', ebiten.KeyBracketRight: '}',
	ebiten.KeyBackslash: '|', ebiten.KeySemicolon: ':',
	ebiten.KeyQuote: '"', ebiten.KeyBackquote: '~',
	ebiten.KeyComma: '<', ebiten.KeyPeriod: '>', ebiten.KeySlash: '?',
	ebiten.KeySpace: ' ',
}

var RUNormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'ф', ebiten.KeyB: 'и', ebiten.KeyC: 'с', ebiten.KeyD: 'в',
	ebiten.KeyE: 'у', ebiten.KeyF: 'а', ebiten.KeyG: 'п', ebiten.KeyH: 'р',
	ebiten.KeyI: 'ш', ebiten.KeyJ: 'о', ebiten.KeyK: 'л', ebiten.KeyL: 'д',
	ebiten.KeyM: 'ь', ebiten.KeyN: 'т', ebiten.KeyO: 'щ', ebiten.KeyP: 'з',
	ebiten.KeyQ: 'й', ebiten.KeyR: 'к', ebiten.KeyS: 'ы', ebiten.KeyT: 'е',
	ebiten.KeyU: 'г', ebiten.KeyV: 'м', ebiten.KeyW: 'ц', ebiten.KeyX: 'ч',
	ebiten.KeyY: 'н', ebiten.KeyZ: 'я',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: 'х', ebiten.KeyBracketRight: 'ъ',
	ebiten.KeyBackslash: '\\', ebiten.KeySemicolon: 'ж',
	ebiten.KeyQuote: 'э', ebiten.KeyBackquote: 'ё',
	ebiten.KeyComma: 'б', ebiten.KeyPeriod: 'ю', ebiten.KeySlash: '.',
	ebiten.KeySpace: ' ',
}

var RUShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'Ф', ebiten.KeyB: 'И', ebiten.KeyC: 'С', ebiten.KeyD: 'В',
	ebiten.KeyE: 'У', ebiten.KeyF: 'А', ebiten.KeyG: 'П', ebiten.KeyH: 'Р',
	ebiten.KeyI: 'Ш', ebiten.KeyJ: 'О', ebiten.KeyK: 'Л', ebiten.KeyL: 'Д',
	ebiten.KeyM: 'Ь', ebiten.KeyN: 'Т', ebiten.KeyO: 'Щ', ebiten.KeyP: 'З',
	ebiten.KeyQ: 'Й', ebiten.KeyR: 'К', ebiten.KeyS: 'Ы', ebiten.KeyT: 'Е',
	ebiten.KeyU: 'Г', ebiten.KeyV: 'М', ebiten.KeyW: 'Ц', ebiten.KeyX: 'Ч',
	ebiten.KeyY: 'Н', ebiten.KeyZ: 'Я',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '"', ebiten.KeyDigit3: '№',
	ebiten.KeyDigit4: ';', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: ':',
	ebiten.KeyDigit7: '?', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: 'Х', ebiten.KeyBracketRight: 'Ъ',
	ebiten.KeyBackslash: '/', ebiten.KeySemicolon: 'Ж',
	ebiten.KeyQuote: 'Э', ebiten.KeyBackquote: 'Ё',
	ebiten.KeyComma: 'Б', ebiten.KeyPeriod: 'Ю', ebiten.KeySlash: ',',
	ebiten.KeySpace: ' ',
}

var UANormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'ф', ebiten.KeyB: 'и', ebiten.KeyC: 'с', ebiten.KeyD: 'в',
	ebiten.KeyE: 'у', ebiten.KeyF: 'а', ebiten.KeyG: 'п', ebiten.KeyH: 'р',
	ebiten.KeyI: 'ш', ebiten.KeyJ: 'о', ebiten.KeyK: 'л', ebiten.KeyL: 'д',
	ebiten.KeyM: 'ь', ebiten.KeyN: 'т', ebiten.KeyO: 'щ', ebiten.KeyP: 'з',
	ebiten.KeyQ: 'й', ebiten.KeyR: 'к', ebiten.KeyS: 'і', ebiten.KeyT: 'е',
	ebiten.KeyU: 'г', ebiten.KeyV: 'м', ebiten.KeyW: 'ц', ebiten.KeyX: 'ч',
	ebiten.KeyY: 'н', ebiten.KeyZ: 'я',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: 'х', ebiten.KeyBracketRight: 'ї',
	ebiten.KeyBackslash: 'ґ', ebiten.KeySemicolon: 'ж',
	ebiten.KeyQuote: 'є', ebiten.KeyBackquote: '\'',
	ebiten.KeyComma: 'б', ebiten.KeyPeriod: 'ю', ebiten.KeySlash: '.',
	ebiten.KeySpace: ' ',
}

var UAShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'Ф', ebiten.KeyB: 'И', ebiten.KeyC: 'С', ebiten.KeyD: 'В',
	ebiten.KeyE: 'У', ebiten.KeyF: 'А', ebiten.KeyG: 'П', ebiten.KeyH: 'Р',
	ebiten.KeyI: 'Ш', ebiten.KeyJ: 'О', ebiten.KeyK: 'Л', ebiten.KeyL: 'Д',
	ebiten.KeyM: 'Ь', ebiten.KeyN: 'Т', ebiten.KeyO: 'Щ', ebiten.KeyP: 'З',
	ebiten.KeyQ: 'Й', ebiten.KeyR: 'К', ebiten.KeyS: 'І', ebiten.KeyT: 'Е',
	ebiten.KeyU: 'Г', ebiten.KeyV: 'М', ebiten.KeyW: 'Ц', ebiten.KeyX: 'Ч',
	ebiten.KeyY: 'Н', ebiten.KeyZ: 'Я',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '"', ebiten.KeyDigit3: '№',
	ebiten.KeyDigit4: ';', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: ':',
	ebiten.KeyDigit7: '?', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: 'Х', ebiten.KeyBracketRight: 'Ї',
	ebiten.KeyBackslash: 'Ґ', ebiten.KeySemicolon: 'Ж',
	ebiten.KeyQuote: 'Є', ebiten.KeyBackquote: 'ʼ',
	ebiten.KeyComma: 'Б', ebiten.KeyPeriod: 'Ю', ebiten.KeySlash: ',',
	ebiten.KeySpace: ' ',
}
