package main

import "github.com/hajimehoshi/ebiten/v2"

var USNormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'a', ebiten.KeyB: 'b', ebiten.KeyC: 'c', ebiten.KeyD: 'd',
	ebiten.KeyE: 'e', ebiten.KeyF: 'f', ebiten.KeyG: 'g', ebiten.KeyH: 'h',
	ebiten.KeyI: 'i', ebiten.KeyJ: 'j', ebiten.KeyK: 'k', ebiten.KeyL: 'l',
	ebiten.KeyM: 'm', ebiten.KeyN: 'n', ebiten.KeyO: 'o', ebiten.KeyP: 'p',
	ebiten.KeyQ: 'q', ebiten.KeyR: 'r', ebiten.KeyS: 's', ebiten.KeyT: 't',
	ebiten.KeyU: 'u', ebiten.KeyV: 'v', ebiten.KeyW: 'w', ebiten.KeyX: 'x',
	ebiten.KeyY: 'y', ebiten.KeyZ: 'z',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: '[', ebiten.KeyBracketRight: ']',
	ebiten.KeyBackslash: '\\', ebiten.KeySemicolon: ';',
	ebiten.KeyQuote: '\'', ebiten.KeyBackquote: '`',
	ebiten.KeyComma: ',', ebiten.KeyPeriod: '.', ebiten.KeySlash: '/',
	ebiten.KeySpace: ' ',
}

var USShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'A', ebiten.KeyB: 'B', ebiten.KeyC: 'C', ebiten.KeyD: 'D',
	ebiten.KeyE: 'E', ebiten.KeyF: 'F', ebiten.KeyG: 'G', ebiten.KeyH: 'H',
	ebiten.KeyI: 'I', ebiten.KeyJ: 'J', ebiten.KeyK: 'K', ebiten.KeyL: 'L',
	ebiten.KeyM: 'M', ebiten.KeyN: 'N', ebiten.KeyO: 'O', ebiten.KeyP: 'P',
	ebiten.KeyQ: 'Q', ebiten.KeyR: 'R', ebiten.KeyS: 'S', ebiten.KeyT: 'T',
	ebiten.KeyU: 'U', ebiten.KeyV: 'V', ebiten.KeyW: 'W', ebiten.KeyX: 'X',
	ebiten.KeyY: 'Y', ebiten.KeyZ: 'Z',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '@', ebiten.KeyDigit3: '#',
	ebiten.KeyDigit4: '$', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: '^',
	ebiten.KeyDigit7: '&', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: '{', ebiten.KeyBracketRight: '}',
	ebiten.KeyBackslash: '|', ebiten.KeySemicolon: ':',
	ebiten.KeyQuote: '"', ebiten.KeyBackquote: '~',
	ebiten.KeyComma: '<', ebiten.KeyPeriod: '>', ebiten.KeySlash: '?',
	ebiten.KeySpace: ' ',
}

var RUNormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'ф', ebiten.KeyB: 'и', ebiten.KeyC: 'с', ebiten.KeyD: 'в',
	ebiten.KeyE: 'у', ebiten.KeyF: 'а', ebiten.KeyG: 'п', ebiten.KeyH: 'р',
	ebiten.KeyI: 'ш', ebiten.KeyJ: 'о', ebiten.KeyK: 'л', ebiten.KeyL: 'д',
	ebiten.KeyM: 'ь', ebiten.KeyN: 'т', ebiten.KeyO: 'щ', ebiten.KeyP: 'з',
	ebiten.KeyQ: 'й', ebiten.KeyR: 'к', ebiten.KeyS: 'ы', ebiten.KeyT: 'е',
	ebiten.KeyU: 'г', ebiten.KeyV: 'м', ebiten.KeyW: 'ц', ebiten.KeyX: 'ч',
	ebiten.KeyY: 'н', ebiten.KeyZ: 'я',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: 'х', ebiten.KeyBracketRight: 'ъ',
	ebiten.KeyBackslash: '\\', ebiten.KeySemicolon: 'ж',
	ebiten.KeyQuote: 'э', ebiten.KeyBackquote: 'ё',
	ebiten.KeyComma: 'б', ebiten.KeyPeriod: 'ю', ebiten.KeySlash: '.',
	ebiten.KeySpace: ' ',
}

var RUShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'Ф', ebiten.KeyB: 'И', ebiten.KeyC: 'С', ebiten.KeyD: 'В',
	ebiten.KeyE: 'У', ebiten.KeyF: 'А', ebiten.KeyG: 'П', ebiten.KeyH: 'Р',
	ebiten.KeyI: 'Ш', ebiten.KeyJ: 'О', ebiten.KeyK: 'Л', ebiten.KeyL: 'Д',
	ebiten.KeyM: 'Ь', ebiten.KeyN: 'Т', ebiten.KeyO: 'Щ', ebiten.KeyP: 'З',
	ebiten.KeyQ: 'Й', ebiten.KeyR: 'К', ebiten.KeyS: 'Ы', ebiten.KeyT: 'Е',
	ebiten.KeyU: 'Г', ebiten.KeyV: 'М', ebiten.KeyW: 'Ц', ebiten.KeyX: 'Ч',
	ebiten.KeyY: 'Н', ebiten.KeyZ: 'Я',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '"', ebiten.KeyDigit3: '№',
	ebiten.KeyDigit4: ';', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: ':',
	ebiten.KeyDigit7: '?', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: 'Х', ebiten.KeyBracketRight: 'Ъ',
	ebiten.KeyBackslash: '/', ebiten.KeySemicolon: 'Ж',
	ebiten.KeyQuote: 'Э', ebiten.KeyBackquote: 'Ё',
	ebiten.KeyComma: 'Б', ebiten.KeyPeriod: 'Ю', ebiten.KeySlash: ',',
	ebiten.KeySpace: ' ',
}

var UANormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'ф', ebiten.KeyB: 'и', ebiten.KeyC: 'с', ebiten.KeyD: 'в',
	ebiten.KeyE: 'у', ebiten.KeyF: 'а', ebiten.KeyG: 'п', ebiten.KeyH: 'р',
	ebiten.KeyI: 'ш', ebiten.KeyJ: 'о', ebiten.KeyK: 'л', ebiten.KeyL: 'д',
	ebiten.KeyM: 'ь', ebiten.KeyN: 'т', ebiten.KeyO: 'щ', ebiten.KeyP: 'з',
	ebiten.KeyQ: 'й', ebiten.KeyR: 'к', ebiten.KeyS: 'і', ebiten.KeyT: 'е',
	ebiten.KeyU: 'г', ebiten.KeyV: 'м', ebiten.KeyW: 'ц', ebiten.KeyX: 'ч',
	ebiten.KeyY: 'н', ebiten.KeyZ: 'я',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: 'х', ebiten.KeyBracketRight: 'ї',
	ebiten.KeyBackslash: 'ґ', ebiten.KeySemicolon: 'ж',
	ebiten.KeyQuote: 'є', ebiten.KeyBackquote: '\'',
	ebiten.KeyComma: 'б', ebiten.KeyPeriod: 'ю', ebiten.KeySlash: '.',
	ebiten.KeySpace: ' ',
}

var UAShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'Ф', ebiten.KeyB: 'И', ebiten.KeyC: 'С', ebiten.KeyD: 'В',
	ebiten.KeyE: 'У', ebiten.KeyF: 'А', ebiten.KeyG: 'П', ebiten.KeyH: 'Р',
	ebiten.KeyI: 'Ш', ebiten.KeyJ: 'О', ebiten.KeyK: 'Л', ebiten.KeyL: 'Д',
	ebiten.KeyM: 'Ь', ebiten.KeyN: 'Т', ebiten.KeyO: 'Щ', ebiten.KeyP: 'З',
	ebiten.KeyQ: 'Й', ebiten.KeyR: 'К', ebiten.KeyS: 'І', ebiten.KeyT: 'Е',
	ebiten.KeyU: 'Г', ebiten.KeyV: 'М', ebiten.KeyW: 'Ц', ebiten.KeyX: 'Ч',
	ebiten.KeyY: 'Н', ebiten.KeyZ: 'Я',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '"', ebiten.KeyDigit3: '№',
	ebiten.KeyDigit4: ';', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: ':',
	ebiten.KeyDigit7: '?', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: 'Х', ebiten.KeyBracketRight: 'Ї',
	ebiten.KeyBackslash: 'Ґ', ebiten.KeySemicolon: 'Ж',
	ebiten.KeyQuote: 'Є', ebiten.KeyBackquote: 'ʼ',
	ebiten.KeyComma: 'Б', ebiten.KeyPeriod: 'Ю', ebiten.KeySlash: ',',
	ebiten.KeySpace: ' ',
}

var USNormalInv = map[rune]ebiten.Key{
	'a': ebiten.KeyA, 'b': ebiten.KeyB, 'c': ebiten.KeyC, 'd': ebiten.KeyD,
	'e': ebiten.KeyE, 'f': ebiten.KeyF, 'g': ebiten.KeyG, 'h': ebiten.KeyH,
	'i': ebiten.KeyI, 'j': ebiten.KeyJ, 'k': ebiten.KeyK, 'l': ebiten.KeyL,
	'm': ebiten.KeyM, 'n': ebiten.KeyN, 'o': ebiten.KeyO, 'p': ebiten.KeyP,
	'q': ebiten.KeyQ, 'r': ebiten.KeyR, 's': ebiten.KeyS, 't': ebiten.KeyT,
	'u': ebiten.KeyU, 'v': ebiten.KeyV, 'w': ebiten.KeyW, 'x': ebiten.KeyX,
	'y': ebiten.KeyY, 'z': ebiten.KeyZ,
	'1': ebiten.KeyDigit1, '2': ebiten.KeyDigit2, '3': ebiten.KeyDigit3,
	'4': ebiten.KeyDigit4, '5': ebiten.KeyDigit5, '6': ebiten.KeyDigit6,
	'7': ebiten.KeyDigit7, '8': ebiten.KeyDigit8, '9': ebiten.KeyDigit9,
	'0': ebiten.KeyDigit0,
	'-': ebiten.KeyMinus, '=': ebiten.KeyEqual,
	'[': ebiten.KeyBracketLeft, ']': ebiten.KeyBracketRight,
	'\\': ebiten.KeyBackslash, ';': ebiten.KeySemicolon,
	'\'': ebiten.KeyQuote, '`': ebiten.KeyBackquote,
	',': ebiten.KeyComma, '.': ebiten.KeyPeriod, '/': ebiten.KeySlash,
	' ': ebiten.KeySpace,
}

var USShiftedInv = map[rune]ebiten.Key{
	'A': ebiten.KeyA, 'B': ebiten.KeyB, 'C': ebiten.KeyC, 'D': ebiten.KeyD,
	'E': ebiten.KeyE, 'F': ebiten.KeyF, 'G': ebiten.KeyG, 'H': ebiten.KeyH,
	'I': ebiten.KeyI, 'J': ebiten.KeyJ, 'K': ebiten.KeyK, 'L': ebiten.KeyL,
	'M': ebiten.KeyM, 'N': ebiten.KeyN, 'O': ebiten.KeyO, 'P': ebiten.KeyP,
	'Q': ebiten.KeyQ, 'R': ebiten.KeyR, 'S': ebiten.KeyS, 'T': ebiten.KeyT,
	'U': ebiten.KeyU, 'V': ebiten.KeyV, 'W': ebiten.KeyW, 'X': ebiten.KeyX,
	'Y': ebiten.KeyY, 'Z': ebiten.KeyZ,
	'!': ebiten.KeyDigit1, '@': ebiten.KeyDigit2, '#': ebiten.KeyDigit3,
	'$': ebiten.KeyDigit4, '%': ebiten.KeyDigit5, '^': ebiten.KeyDigit6,
	'&': ebiten.KeyDigit7, '*': ebiten.KeyDigit8, '(': ebiten.KeyDigit9,
	')': ebiten.KeyDigit0,
	'_': ebiten.KeyMinus, '+': ebiten.KeyEqual,
	'{': ebiten.KeyBracketLeft, '}': ebiten.KeyBracketRight,
	'|': ebiten.KeyBackslash, ':': ebiten.KeySemicolon,
	'"': ebiten.KeyQuote, '~': ebiten.KeyBackquote,
	'<': ebiten.KeyComma, '>': ebiten.KeyPeriod, '?': ebiten.KeySlash,
	' ': ebiten.KeySpace,
}

var RUNormalInv = map[rune]ebiten.Key{
	'ф': ebiten.KeyA, 'и': ebiten.KeyB, 'с': ebiten.KeyC, 'в': ebiten.KeyD,
	'у': ebiten.KeyE, 'а': ebiten.KeyF, 'п': ebiten.KeyG, 'р': ebiten.KeyH,
	'ш': ebiten.KeyI, 'о': ebiten.KeyJ, 'л': ebiten.KeyK, 'д': ebiten.KeyL,
	'ь': ebiten.KeyM, 'т': ebiten.KeyN, 'щ': ebiten.KeyO, 'з': ebiten.KeyP,
	'й': ebiten.KeyQ, 'к': ebiten.KeyR, 'ы': ebiten.KeyS, 'е': ebiten.KeyT,
	'г': ebiten.KeyU, 'м': ebiten.KeyV, 'ц': ebiten.KeyW, 'ч': ebiten.KeyX,
	'н': ebiten.KeyY, 'я': ebiten.KeyZ,
	'1': ebiten.KeyDigit1, '2': ebiten.KeyDigit2, '3': ebiten.KeyDigit3,
	'4': ebiten.KeyDigit4, '5': ebiten.KeyDigit5, '6': ebiten.KeyDigit6,
	'7': ebiten.KeyDigit7, '8': ebiten.KeyDigit8, '9': ebiten.KeyDigit9,
	'0': ebiten.KeyDigit0,
	'-': ebiten.KeyMinus, '=': ebiten.KeyEqual,
	'х': ebiten.KeyBracketLeft, 'ъ': ebiten.KeyBracketRight,
	'\\': ebiten.KeyBackslash, 'ж': ebiten.KeySemicolon,
	'э': ebiten.KeyQuote, 'ё': ebiten.KeyBackquote,
	'б': ebiten.KeyComma, 'ю': ebiten.KeyPeriod, '.': ebiten.KeySlash,
	' ': ebiten.KeySpace,
}

var RUShiftedInv = map[rune]ebiten.Key{
	'Ф': ebiten.KeyA, 'И': ebiten.KeyB, 'С': ebiten.KeyC, 'В': ebiten.KeyD,
	'У': ebiten.KeyE, 'А': ebiten.KeyF, 'П': ebiten.KeyG, 'Р': ebiten.KeyH,
	'Ш': ebiten.KeyI, 'О': ebiten.KeyJ, 'Л': ebiten.KeyK, 'Д': ebiten.KeyL,
	'Ь': ebiten.KeyM, 'Т': ebiten.KeyN, 'Щ': ebiten.KeyO, 'З': ebiten.KeyP,
	'Й': ebiten.KeyQ, 'К': ebiten.KeyR, 'Ы': ebiten.KeyS, 'Е': ebiten.KeyT,
	'Г': ebiten.KeyU, 'М': ebiten.KeyV, 'Ц': ebiten.KeyW, 'Ч': ebiten.KeyX,
	'Н': ebiten.KeyY, 'Я': ebiten.KeyZ,
	'!': ebiten.KeyDigit1, '"': ebiten.KeyDigit2, '№': ebiten.KeyDigit3,
	';': ebiten.KeyDigit4, '%': ebiten.KeyDigit5, ':': ebiten.KeyDigit6,
	'?': ebiten.KeyDigit7, '*': ebiten.KeyDigit8, '(': ebiten.KeyDigit9,
	')': ebiten.KeyDigit0,
	'_': ebiten.KeyMinus, '+': ebiten.KeyEqual,
	'Х': ebiten.KeyBracketLeft, 'Ъ': ebiten.KeyBracketRight,
	'/': ebiten.KeyBackslash, 'Ж': ebiten.KeySemicolon,
	'Э': ebiten.KeyQuote, 'Ё': ebiten.KeyBackquote,
	'Б': ebiten.KeyComma, 'Ю': ebiten.KeyPeriod, ',': ebiten.KeySlash,
	' ': ebiten.KeySpace,
}

var UANormalInv = map[rune]ebiten.Key{
	'ф': ebiten.KeyA, 'и': ebiten.KeyB, 'с': ebiten.KeyC, 'в': ebiten.KeyD,
	'у': ebiten.KeyE, 'а': ebiten.KeyF, 'п': ebiten.KeyG, 'р': ebiten.KeyH,
	'ш': ebiten.KeyI, 'о': ebiten.KeyJ, 'л': ebiten.KeyK, 'д': ebiten.KeyL,
	'ь': ebiten.KeyM, 'т': ebiten.KeyN, 'щ': ebiten.KeyO, 'з': ebiten.KeyP,
	'й': ebiten.KeyQ, 'к': ebiten.KeyR, 'і': ebiten.KeyS, 'е': ebiten.KeyT,
	'г': ebiten.KeyU, 'м': ebiten.KeyV, 'ц': ebiten.KeyW, 'ч': ebiten.KeyX,
	'н': ebiten.KeyY, 'я': ebiten.KeyZ,
	'1': ebiten.KeyDigit1, '2': ebiten.KeyDigit2, '3': ebiten.KeyDigit3,
	'4': ebiten.KeyDigit4, '5': ebiten.KeyDigit5, '6': ebiten.KeyDigit6,
	'7': ebiten.KeyDigit7, '8': ebiten.KeyDigit8, '9': ebiten.KeyDigit9,
	'0': ebiten.KeyDigit0,
	'-': ebiten.KeyMinus, '=': ebiten.KeyEqual,
	'х': ebiten.KeyBracketLeft, 'ї': ebiten.KeyBracketRight,
	'ґ': ebiten.KeyBackslash, 'ж': ebiten.KeySemicolon,
	'є': ebiten.KeyQuote, '\'': ebiten.KeyBackquote,
	'б': ebiten.KeyComma, 'ю': ebiten.KeyPeriod, '.': ebiten.KeySlash,
	' ': ebiten.KeySpace,
}

var UAShiftedInv = map[rune]ebiten.Key{
	'Ф': ebiten.KeyA, 'И': ebiten.KeyB, 'С': ebiten.KeyC, 'В': ebiten.KeyD,
	'У': ebiten.KeyE, 'А': ebiten.KeyF, 'П': ebiten.KeyG, 'Р': ebiten.KeyH,
	'Ш': ebiten.KeyI, 'О': ebiten.KeyJ, 'Л': ebiten.KeyK, 'Д': ebiten.KeyL,
	'Ь': ebiten.KeyM, 'Т': ebiten.KeyN, 'Щ': ebiten.KeyO, 'З': ebiten.KeyP,
	'Й': ebiten.KeyQ, 'К': ebiten.KeyR, 'І': ebiten.KeyS, 'Е': ebiten.KeyT,
	'Г': ebiten.KeyU, 'М': ebiten.KeyV, 'Ц': ebiten.KeyW, 'Ч': ebiten.KeyX,
	'Н': ebiten.KeyY, 'Я': ebiten.KeyZ,
	'!': ebiten.KeyDigit1, '"': ebiten.KeyDigit2, '№': ebiten.KeyDigit3,
	';': ebiten.KeyDigit4, '%': ebiten.KeyDigit5, ':': ebiten.KeyDigit6,
	'?': ebiten.KeyDigit7, '*': ebiten.KeyDigit8, '(': ebiten.KeyDigit9,
	')': ebiten.KeyDigit0,
	'_': ebiten.KeyMinus, '+': ebiten.KeyEqual,
	'Х': ebiten.KeyBracketLeft, 'Ї': ebiten.KeyBracketRight,
	'Ґ': ebiten.KeyBackslash, 'Ж': ebiten.KeySemicolon,
	'Є': ebiten.KeyQuote, 'ʼ': ebiten.KeyBackquote,
	'Б': ebiten.KeyComma, 'Ю': ebiten.KeyPeriod, ',': ebiten.KeySlash,
	' ': ebiten.KeySpace,
}
