package main

import "github.com/hajimehoshi/ebiten/v2"

type KeyWithShift struct {
	Key   ebiten.Key
	Shift bool
}

var USNormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'a', ebiten.KeyB: 'b', ebiten.KeyC: 'c', ebiten.KeyD: 'd',
	ebiten.KeyE: 'e', ebiten.KeyF: 'f', ebiten.KeyG: 'g', ebiten.KeyH: 'h',
	ebiten.KeyI: 'i', ebiten.KeyJ: 'j', ebiten.KeyK: 'k', ebiten.KeyL: 'l',
	ebiten.KeyM: 'm', ebiten.KeyN: 'n', ebiten.KeyO: 'o', ebiten.KeyP: 'p',
	ebiten.KeyQ: 'q', ebiten.KeyR: 'r', ebiten.KeyS: 's', ebiten.KeyT: 't',
	ebiten.KeyU: 'u', ebiten.KeyV: 'v', ebiten.KeyW: 'w', ebiten.KeyX: 'x',
	ebiten.KeyY: 'y', ebiten.KeyZ: 'z',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: '[', ebiten.KeyBracketRight: ']',
	ebiten.KeyBackslash: '\\', ebiten.KeySemicolon: ';',
	ebiten.KeyQuote: '\'', ebiten.KeyBackquote: '`',
	ebiten.KeyComma: ',', ebiten.KeyPeriod: '.', ebiten.KeySlash: '/',
	ebiten.KeySpace: ' ',
}

var USShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'A', ebiten.KeyB: 'B', ebiten.KeyC: 'C', ebiten.KeyD: 'D',
	ebiten.KeyE: 'E', ebiten.KeyF: 'F', ebiten.KeyG: 'G', ebiten.KeyH: 'H',
	ebiten.KeyI: 'I', ebiten.KeyJ: 'J', ebiten.KeyK: 'K', ebiten.KeyL: 'L',
	ebiten.KeyM: 'M', ebiten.KeyN: 'N', ebiten.KeyO: 'O', ebiten.KeyP: 'P',
	ebiten.KeyQ: 'Q', ebiten.KeyR: 'R', ebiten.KeyS: 'S', ebiten.KeyT: 'T',
	ebiten.KeyU: 'U', ebiten.KeyV: 'V', ebiten.KeyW: 'W', ebiten.KeyX: 'X',
	ebiten.KeyY: 'Y', ebiten.KeyZ: 'Z',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '@', ebiten.KeyDigit3: '#',
	ebiten.KeyDigit4: '$', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: '^',
	ebiten.KeyDigit7: '&', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: '{', ebiten.KeyBracketRight: '}',
	ebiten.KeyBackslash: '|', ebiten.KeySemicolon: ':',
	ebiten.KeyQuote: '"', ebiten.KeyBackquote: '~',
	ebiten.KeyComma: '<', ebiten.KeyPeriod: '>', ebiten.KeySlash: '?',
	ebiten.KeySpace: ' ',
}

var RUNormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'ф', ebiten.KeyB: 'и', ebiten.KeyC: 'с', ebiten.KeyD: 'в',
	ebiten.KeyE: 'у', ebiten.KeyF: 'а', ebiten.KeyG: 'п', ebiten.KeyH: 'р',
	ebiten.KeyI: 'ш', ebiten.KeyJ: 'о', ebiten.KeyK: 'л', ebiten.KeyL: 'д',
	ebiten.KeyM: 'ь', ebiten.KeyN: 'т', ebiten.KeyO: 'щ', ebiten.KeyP: 'з',
	ebiten.KeyQ: 'й', ebiten.KeyR: 'к', ebiten.KeyS: 'ы', ebiten.KeyT: 'е',
	ebiten.KeyU: 'г', ebiten.KeyV: 'м', ebiten.KeyW: 'ц', ebiten.KeyX: 'ч',
	ebiten.KeyY: 'н', ebiten.KeyZ: 'я',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: 'х', ebiten.KeyBracketRight: 'ъ',
	ebiten.KeyBackslash: '\\', ebiten.KeySemicolon: 'ж',
	ebiten.KeyQuote: 'э', ebiten.KeyBackquote: 'ё',
	ebiten.KeyComma: 'б', ebiten.KeyPeriod: 'ю', ebiten.KeySlash: '.',
	ebiten.KeySpace: ' ',
}

var RUShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'Ф', ebiten.KeyB: 'И', ebiten.KeyC: 'С', ebiten.KeyD: 'В',
	ebiten.KeyE: 'У', ebiten.KeyF: 'А', ebiten.KeyG: 'П', ebiten.KeyH: 'Р',
	ebiten.KeyI: 'Ш', ebiten.KeyJ: 'О', ebiten.KeyK: 'Л', ebiten.KeyL: 'Д',
	ebiten.KeyM: 'Ь', ebiten.KeyN: 'Т', ebiten.KeyO: 'Щ', ebiten.KeyP: 'З',
	ebiten.KeyQ: 'Й', ebiten.KeyR: 'К', ebiten.KeyS: 'Ы', ebiten.KeyT: 'Е',
	ebiten.KeyU: 'Г', ebiten.KeyV: 'М', ebiten.KeyW: 'Ц', ebiten.KeyX: 'Ч',
	ebiten.KeyY: 'Н', ebiten.KeyZ: 'Я',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '"', ebiten.KeyDigit3: '№',
	ebiten.KeyDigit4: ';', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: ':',
	ebiten.KeyDigit7: '?', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: 'Х', ebiten.KeyBracketRight: 'Ъ',
	ebiten.KeyBackslash: '/', ebiten.KeySemicolon: 'Ж',
	ebiten.KeyQuote: 'Э', ebiten.KeyBackquote: 'Ё',
	ebiten.KeyComma: 'Б', ebiten.KeyPeriod: 'Ю', ebiten.KeySlash: ',',
	ebiten.KeySpace: ' ',
}

var UANormal = map[ebiten.Key]rune{
	ebiten.KeyA: 'ф', ebiten.KeyB: 'и', ebiten.KeyC: 'с', ebiten.KeyD: 'в',
	ebiten.KeyE: 'у', ebiten.KeyF: 'а', ebiten.KeyG: 'п', ebiten.KeyH: 'р',
	ebiten.KeyI: 'ш', ebiten.KeyJ: 'о', ebiten.KeyK: 'л', ebiten.KeyL: 'д',
	ebiten.KeyM: 'ь', ebiten.KeyN: 'т', ebiten.KeyO: 'щ', ebiten.KeyP: 'з',
	ebiten.KeyQ: 'й', ebiten.KeyR: 'к', ebiten.KeyS: 'і', ebiten.KeyT: 'е',
	ebiten.KeyU: 'г', ebiten.KeyV: 'м', ebiten.KeyW: 'ц', ebiten.KeyX: 'ч',
	ebiten.KeyY: 'н', ebiten.KeyZ: 'я',
	ebiten.KeyDigit1: '1', ebiten.KeyDigit2: '2', ebiten.KeyDigit3: '3',
	ebiten.KeyDigit4: '4', ebiten.KeyDigit5: '5', ebiten.KeyDigit6: '6',
	ebiten.KeyDigit7: '7', ebiten.KeyDigit8: '8', ebiten.KeyDigit9: '9',
	ebiten.KeyDigit0: '0',
	ebiten.KeyMinus:  '-', ebiten.KeyEqual: '=',
	ebiten.KeyBracketLeft: 'х', ebiten.KeyBracketRight: 'ї',
	ebiten.KeyBackslash: 'ґ', ebiten.KeySemicolon: 'ж',
	ebiten.KeyQuote: 'є', ebiten.KeyBackquote: '\'',
	ebiten.KeyComma: 'б', ebiten.KeyPeriod: 'ю', ebiten.KeySlash: '.',
	ebiten.KeySpace: ' ',
}

var UAShifted = map[ebiten.Key]rune{
	ebiten.KeyA: 'Ф', ebiten.KeyB: 'И', ebiten.KeyC: 'С', ebiten.KeyD: 'В',
	ebiten.KeyE: 'У', ebiten.KeyF: 'А', ebiten.KeyG: 'П', ebiten.KeyH: 'Р',
	ebiten.KeyI: 'Ш', ebiten.KeyJ: 'О', ebiten.KeyK: 'Л', ebiten.KeyL: 'Д',
	ebiten.KeyM: 'Ь', ebiten.KeyN: 'Т', ebiten.KeyO: 'Щ', ebiten.KeyP: 'З',
	ebiten.KeyQ: 'Й', ebiten.KeyR: 'К', ebiten.KeyS: 'І', ebiten.KeyT: 'Е',
	ebiten.KeyU: 'Г', ebiten.KeyV: 'М', ebiten.KeyW: 'Ц', ebiten.KeyX: 'Ч',
	ebiten.KeyY: 'Н', ebiten.KeyZ: 'Я',
	ebiten.KeyDigit1: '!', ebiten.KeyDigit2: '"', ebiten.KeyDigit3: '№',
	ebiten.KeyDigit4: ';', ebiten.KeyDigit5: '%', ebiten.KeyDigit6: ':',
	ebiten.KeyDigit7: '?', ebiten.KeyDigit8: '*', ebiten.KeyDigit9: '(',
	ebiten.KeyDigit0: ')',
	ebiten.KeyMinus:  '_', ebiten.KeyEqual: '+',
	ebiten.KeyBracketLeft: 'Х', ebiten.KeyBracketRight: 'Ї',
	ebiten.KeyBackslash: 'Ґ', ebiten.KeySemicolon: 'Ж',
	ebiten.KeyQuote: 'Є', ebiten.KeyBackquote: 'ʼ',
	ebiten.KeyComma: 'Б', ebiten.KeyPeriod: 'Ю', ebiten.KeySlash: ',',
	ebiten.KeySpace: ' ',
}

var USKeyMap = map[rune]KeyWithShift{
	'a': {Key: ebiten.KeyA, Shift: false}, 'b': {Key: ebiten.KeyB, Shift: false}, 'c': {Key: ebiten.KeyC, Shift: false}, 'd': {Key: ebiten.KeyD, Shift: false},
	'e': {Key: ebiten.KeyE, Shift: false}, 'f': {Key: ebiten.KeyF, Shift: false}, 'g': {Key: ebiten.KeyG, Shift: false}, 'h': {Key: ebiten.KeyH, Shift: false},
	'i': {Key: ebiten.KeyI, Shift: false}, 'j': {Key: ebiten.KeyJ, Shift: false}, 'k': {Key: ebiten.KeyK, Shift: false}, 'l': {Key: ebiten.KeyL, Shift: false},
	'm': {Key: ebiten.KeyM, Shift: false}, 'n': {Key: ebiten.KeyN, Shift: false}, 'o': {Key: ebiten.KeyO, Shift: false}, 'p': {Key: ebiten.KeyP, Shift: false},
	'q': {Key: ebiten.KeyQ, Shift: false}, 'r': {Key: ebiten.KeyR, Shift: false}, 's': {Key: ebiten.KeyS, Shift: false}, 't': {Key: ebiten.KeyT, Shift: false},
	'u': {Key: ebiten.KeyU, Shift: false}, 'v': {Key: ebiten.KeyV, Shift: false}, 'w': {Key: ebiten.KeyW, Shift: false}, 'x': {Key: ebiten.KeyX, Shift: false},
	'y': {Key: ebiten.KeyY, Shift: false}, 'z': {Key: ebiten.KeyZ, Shift: false},
	'A': {Key: ebiten.KeyA, Shift: true}, 'B': {Key: ebiten.KeyB, Shift: true}, 'C': {Key: ebiten.KeyC, Shift: true}, 'D': {Key: ebiten.KeyD, Shift: true},
	'E': {Key: ebiten.KeyE, Shift: true}, 'F': {Key: ebiten.KeyF, Shift: true}, 'G': {Key: ebiten.KeyG, Shift: true}, 'H': {Key: ebiten.KeyH, Shift: true},
	'I': {Key: ebiten.KeyI, Shift: true}, 'J': {Key: ebiten.KeyJ, Shift: true}, 'K': {Key: ebiten.KeyK, Shift: true}, 'L': {Key: ebiten.KeyL, Shift: true},
	'M': {Key: ebiten.KeyM, Shift: true}, 'N': {Key: ebiten.KeyN, Shift: true}, 'O': {Key: ebiten.KeyO, Shift: true}, 'P': {Key: ebiten.KeyP, Shift: true},
	'Q': {Key: ebiten.KeyQ, Shift: true}, 'R': {Key: ebiten.KeyR, Shift: true}, 'S': {Key: ebiten.KeyS, Shift: true}, 'T': {Key: ebiten.KeyT, Shift: true},
	'U': {Key: ebiten.KeyU, Shift: true}, 'V': {Key: ebiten.KeyV, Shift: true}, 'W': {Key: ebiten.KeyW, Shift: true}, 'X': {Key: ebiten.KeyX, Shift: true},
	'Y': {Key: ebiten.KeyY, Shift: true}, 'Z': {Key: ebiten.KeyZ, Shift: true},
	'1': {Key: ebiten.KeyDigit1, Shift: false}, '2': {Key: ebiten.KeyDigit2, Shift: false}, '3': {Key: ebiten.KeyDigit3, Shift: false},
	'4': {Key: ebiten.KeyDigit4, Shift: false}, '5': {Key: ebiten.KeyDigit5, Shift: false}, '6': {Key: ebiten.KeyDigit6, Shift: false},
	'7': {Key: ebiten.KeyDigit7, Shift: false}, '8': {Key: ebiten.KeyDigit8, Shift: false}, '9': {Key: ebiten.KeyDigit9, Shift: false},
	'0': {Key: ebiten.KeyDigit0, Shift: false},
	'!': {Key: ebiten.KeyDigit1, Shift: true}, '@': {Key: ebiten.KeyDigit2, Shift: true}, '#': {Key: ebiten.KeyDigit3, Shift: true},
	'$': {Key: ebiten.KeyDigit4, Shift: true}, '%': {Key: ebiten.KeyDigit5, Shift: true}, '^': {Key: ebiten.KeyDigit6, Shift: true},
	'&': {Key: ebiten.KeyDigit7, Shift: true}, '*': {Key: ebiten.KeyDigit8, Shift: true}, '(': {Key: ebiten.KeyDigit9, Shift: true},
	')': {Key: ebiten.KeyDigit0, Shift: true},
	'-': {Key: ebiten.KeyMinus, Shift: false}, '=': {Key: ebiten.KeyEqual, Shift: false},
	'_': {Key: ebiten.KeyMinus, Shift: true}, '+': {Key: ebiten.KeyEqual, Shift: true},
	'[': {Key: ebiten.KeyBracketLeft, Shift: false}, ']': {Key: ebiten.KeyBracketRight, Shift: false},
	'{': {Key: ebiten.KeyBracketLeft, Shift: true}, '}': {Key: ebiten.KeyBracketRight, Shift: true},
	'\\': {Key: ebiten.KeyBackslash, Shift: false}, '|': {Key: ebiten.KeyBackslash, Shift: true},
	';': {Key: ebiten.KeySemicolon, Shift: false}, ':': {Key: ebiten.KeySemicolon, Shift: true},
	'\'': {Key: ebiten.KeyQuote, Shift: false}, '"': {Key: ebiten.KeyQuote, Shift: true},
	'`': {Key: ebiten.KeyBackquote, Shift: false}, '~': {Key: ebiten.KeyBackquote, Shift: true},
	',': {Key: ebiten.KeyComma, Shift: false}, '<': {Key: ebiten.KeyComma, Shift: true},
	'.': {Key: ebiten.KeyPeriod, Shift: false}, '>': {Key: ebiten.KeyPeriod, Shift: true},
	'/': {Key: ebiten.KeySlash, Shift: false}, '?': {Key: ebiten.KeySlash, Shift: true},
	' ': {Key: ebiten.KeySpace, Shift: false},
}

var RUKeyMap = map[rune]KeyWithShift{
	'ф': {Key: ebiten.KeyA, Shift: false}, 'и': {Key: ebiten.KeyB, Shift: false}, 'с': {Key: ebiten.KeyC, Shift: false}, 'в': {Key: ebiten.KeyD, Shift: false},
	'у': {Key: ebiten.KeyE, Shift: false}, 'а': {Key: ebiten.KeyF, Shift: false}, 'п': {Key: ebiten.KeyG, Shift: false}, 'р': {Key: ebiten.KeyH, Shift: false},
	'ш': {Key: ebiten.KeyI, Shift: false}, 'о': {Key: ebiten.KeyJ, Shift: false}, 'л': {Key: ebiten.KeyK, Shift: false}, 'д': {Key: ebiten.KeyL, Shift: false},
	'ь': {Key: ebiten.KeyM, Shift: false}, 'т': {Key: ebiten.KeyN, Shift: false}, 'щ': {Key: ebiten.KeyO, Shift: false}, 'з': {Key: ebiten.KeyP, Shift: false},
	'й': {Key: ebiten.KeyQ, Shift: false}, 'к': {Key: ebiten.KeyR, Shift: false}, 'ы': {Key: ebiten.KeyS, Shift: false}, 'е': {Key: ebiten.KeyT, Shift: false},
	'г': {Key: ebiten.KeyU, Shift: false}, 'м': {Key: ebiten.KeyV, Shift: false}, 'ц': {Key: ebiten.KeyW, Shift: false}, 'ч': {Key: ebiten.KeyX, Shift: false},
	'н': {Key: ebiten.KeyY, Shift: false}, 'я': {Key: ebiten.KeyZ, Shift: false},
	'Ф': {Key: ebiten.KeyA, Shift: true}, 'И': {Key: ebiten.KeyB, Shift: true}, 'С': {Key: ebiten.KeyC, Shift: true}, 'В': {Key: ebiten.KeyD, Shift: true},
	'У': {Key: ebiten.KeyE, Shift: true}, 'А': {Key: ebiten.KeyF, Shift: true}, 'П': {Key: ebiten.KeyG, Shift: true}, 'Р': {Key: ebiten.KeyH, Shift: true},
	'Ш': {Key: ebiten.KeyI, Shift: true}, 'О': {Key: ebiten.KeyJ, Shift: true}, 'Л': {Key: ebiten.KeyK, Shift: true}, 'Д': {Key: ebiten.KeyL, Shift: true},
	'Ь': {Key: ebiten.KeyM, Shift: true}, 'Т': {Key: ebiten.KeyN, Shift: true}, 'Щ': {Key: ebiten.KeyO, Shift: true}, 'З': {Key: ebiten.KeyP, Shift: true},
	'Й': {Key: ebiten.KeyQ, Shift: true}, 'К': {Key: ebiten.KeyR, Shift: true}, 'Ы': {Key: ebiten.KeyS, Shift: true}, 'Е': {Key: ebiten.KeyT, Shift: true},
	'Г': {Key: ebiten.KeyU, Shift: true}, 'М': {Key: ebiten.KeyV, Shift: true}, 'Ц': {Key: ebiten.KeyW, Shift: true}, 'Ч': {Key: ebiten.KeyX, Shift: true},
	'Н': {Key: ebiten.KeyY, Shift: true}, 'Я': {Key: ebiten.KeyZ, Shift: true},
	'1': {Key: ebiten.KeyDigit1, Shift: false}, '2': {Key: ebiten.KeyDigit2, Shift: false}, '3': {Key: ebiten.KeyDigit3, Shift: false},
	'4': {Key: ebiten.KeyDigit4, Shift: false}, '5': {Key: ebiten.KeyDigit5, Shift: false}, '6': {Key: ebiten.KeyDigit6, Shift: false},
	'7': {Key: ebiten.KeyDigit7, Shift: false}, '8': {Key: ebiten.KeyDigit8, Shift: false}, '9': {Key: ebiten.KeyDigit9, Shift: false},
	'0': {Key: ebiten.KeyDigit0, Shift: false},
	'!': {Key: ebiten.KeyDigit1, Shift: true}, '"': {Key: ebiten.KeyDigit2, Shift: true}, '№': {Key: ebiten.KeyDigit3, Shift: true},
	';': {Key: ebiten.KeyDigit4, Shift: true}, '%': {Key: ebiten.KeyDigit5, Shift: true}, ':': {Key: ebiten.KeyDigit6, Shift: true},
	'?': {Key: ebiten.KeyDigit7, Shift: true}, '*': {Key: ebiten.KeyDigit8, Shift: true}, '(': {Key: ebiten.KeyDigit9, Shift: true},
	')': {Key: ebiten.KeyDigit0, Shift: true},
	'-': {Key: ebiten.KeyMinus, Shift: false}, '=': {Key: ebiten.KeyEqual, Shift: false},
	'х': {Key: ebiten.KeyBracketLeft, Shift: false}, 'ъ': {Key: ebiten.KeyBracketRight, Shift: false},
	'Х': {Key: ebiten.KeyBracketLeft, Shift: true}, 'Ъ': {Key: ebiten.KeyBracketRight, Shift: true},
	'\\': {Key: ebiten.KeyBackslash, Shift: false}, '/': {Key: ebiten.KeyBackslash, Shift: true},
	'ж': {Key: ebiten.KeySemicolon, Shift: false}, 'Ж': {Key: ebiten.KeySemicolon, Shift: true},
	'э': {Key: ebiten.KeyQuote, Shift: false}, 'Э': {Key: ebiten.KeyQuote, Shift: true},
	'ё': {Key: ebiten.KeyBackquote, Shift: false}, 'Ё': {Key: ebiten.KeyBackquote, Shift: true},
	'б': {Key: ebiten.KeyComma, Shift: false}, 'Б': {Key: ebiten.KeyComma, Shift: true},
	'ю': {Key: ebiten.KeyPeriod, Shift: false}, 'Ю': {Key: ebiten.KeyPeriod, Shift: true},
	'.': {Key: ebiten.KeySlash, Shift: false}, ',': {Key: ebiten.KeySlash, Shift: true},
	' ': {Key: ebiten.KeySpace, Shift: false},
}

var UAKeyMap = map[rune]KeyWithShift{
	'ф': {Key: ebiten.KeyA, Shift: false}, 'и': {Key: ebiten.KeyB, Shift: false}, 'с': {Key: ebiten.KeyC, Shift: false}, 'в': {Key: ebiten.KeyD, Shift: false},
	'у': {Key: ebiten.KeyE, Shift: false}, 'а': {Key: ebiten.KeyF, Shift: false}, 'п': {Key: ebiten.KeyG, Shift: false}, 'р': {Key: ebiten.KeyH, Shift: false},
	'ш': {Key: ebiten.KeyI, Shift: false}, 'о': {Key: ebiten.KeyJ, Shift: false}, 'л': {Key: ebiten.KeyK, Shift: false}, 'д': {Key: ebiten.KeyL, Shift: false},
	'ь': {Key: ebiten.KeyM, Shift: false}, 'т': {Key: ebiten.KeyN, Shift: false}, 'щ': {Key: ebiten.KeyO, Shift: false}, 'з': {Key: ebiten.KeyP, Shift: false},
	'й': {Key: ebiten.KeyQ, Shift: false}, 'к': {Key: ebiten.KeyR, Shift: false}, 'і': {Key: ebiten.KeyS, Shift: false}, 'е': {Key: ebiten.KeyT, Shift: false},
	'г': {Key: ebiten.KeyU, Shift: false}, 'м': {Key: ebiten.KeyV, Shift: false}, 'ц': {Key: ebiten.KeyW, Shift: false}, 'ч': {Key: ebiten.KeyX, Shift: false},
	'н': {Key: ebiten.KeyY, Shift: false}, 'я': {Key: ebiten.KeyZ, Shift: false},
	'Ф': {Key: ebiten.KeyA, Shift: true}, 'И': {Key: ebiten.KeyB, Shift: true}, 'С': {Key: ebiten.KeyC, Shift: true}, 'В': {Key: ebiten.KeyD, Shift: true},
	'У': {Key: ebiten.KeyE, Shift: true}, 'А': {Key: ebiten.KeyF, Shift: true}, 'П': {Key: ebiten.KeyG, Shift: true}, 'Р': {Key: ebiten.KeyH, Shift: true},
	'Ш': {Key: ebiten.KeyI, Shift: true}, 'О': {Key: ebiten.KeyJ, Shift: true}, 'Л': {Key: ebiten.KeyK, Shift: true}, 'Д': {Key: ebiten.KeyL, Shift: true},
	'Ь': {Key: ebiten.KeyM, Shift: true}, 'Т': {Key: ebiten.KeyN, Shift: true}, 'Щ': {Key: ebiten.KeyO, Shift: true}, 'З': {Key: ebiten.KeyP, Shift: true},
	'Й': {Key: ebiten.KeyQ, Shift: true}, 'К': {Key: ebiten.KeyR, Shift: true}, 'І': {Key: ebiten.KeyS, Shift: true}, 'Е': {Key: ebiten.KeyT, Shift: true},
	'Г': {Key: ebiten.KeyU, Shift: true}, 'М': {Key: ebiten.KeyV, Shift: true}, 'Ц': {Key: ebiten.KeyW, Shift: true}, 'Ч': {Key: ebiten.KeyX, Shift: true},
	'Н': {Key: ebiten.KeyY, Shift: true}, 'Я': {Key: ebiten.KeyZ, Shift: true},
	'1': {Key: ebiten.KeyDigit1, Shift: false}, '2': {Key: ebiten.KeyDigit2, Shift: false}, '3': {Key: ebiten.KeyDigit3, Shift: false},
	'4': {Key: ebiten.KeyDigit4, Shift: false}, '5': {Key: ebiten.KeyDigit5, Shift: false}, '6': {Key: ebiten.KeyDigit6, Shift: false},
	'7': {Key: ebiten.KeyDigit7, Shift: false}, '8': {Key: ebiten.KeyDigit8, Shift: false}, '9': {Key: ebiten.KeyDigit9, Shift: false},
	'0': {Key: ebiten.KeyDigit0, Shift: false},
	'!': {Key: ebiten.KeyDigit1, Shift: true}, '"': {Key: ebiten.KeyDigit2, Shift: true}, '№': {Key: ebiten.KeyDigit3, Shift: true},
	';': {Key: ebiten.KeyDigit4, Shift: true}, '%': {Key: ebiten.KeyDigit5, Shift: true}, ':': {Key: ebiten.KeyDigit6, Shift: true},
	'?': {Key: ebiten.KeyDigit7, Shift: true}, '*': {Key: ebiten.KeyDigit8, Shift: true}, '(': {Key: ebiten.KeyDigit9, Shift: true},
	')': {Key: ebiten.KeyDigit0, Shift: true},
	'-': {Key: ebiten.KeyMinus, Shift: false}, '=': {Key: ebiten.KeyEqual, Shift: false},
	'х': {Key: ebiten.KeyBracketLeft, Shift: false}, 'ї': {Key: ebiten.KeyBracketRight, Shift: false},
	'Х': {Key: ebiten.KeyBracketLeft, Shift: true}, 'Ї': {Key: ebiten.KeyBracketRight, Shift: true},
	'ґ': {Key: ebiten.KeyBackslash, Shift: false}, 'Ґ': {Key: ebiten.KeyBackslash, Shift: true},
	'ж': {Key: ebiten.KeySemicolon, Shift: false}, 'Ж': {Key: ebiten.KeySemicolon, Shift: true},
	'є': {Key: ebiten.KeyQuote, Shift: false}, 'Є': {Key: ebiten.KeyQuote, Shift: true},
	'\'': {Key: ebiten.KeyBackquote, Shift: false}, 'ʼ': {Key: ebiten.KeyBackquote, Shift: true},
	'б': {Key: ebiten.KeyComma, Shift: false}, 'Б': {Key: ebiten.KeyComma, Shift: true},
	'ю': {Key: ebiten.KeyPeriod, Shift: false}, 'Ю': {Key: ebiten.KeyPeriod, Shift: true},
	'.': {Key: ebiten.KeySlash, Shift: false}, ',': {Key: ebiten.KeySlash, Shift: true},
	' ': {Key: ebiten.KeySpace, Shift: false},
}
